apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: nvidia/cuda:12.5.0-base-ubuntu22.04
        resources:
          limits:
            nvidia.com/gpu: 1 # Request 1 GPU
        command: ["nvidia-smi"]
      restartPolicy: Never